[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bundle exec puma -C config/puma.rb"
restartPolicyType = "on_failure"
watchPatterns = ["**", "!frontend/**", "!**/*.md"]
